const fontWeights = {
  normal: 500,
  medium: 600,
  semibold: 700,
};

export const ThemeText = {
  headingLg: {
    fontFamily: "Inter, sans-serif",
    fontWeight: fontWeights.semibold,
    fontSize: "20px",
    lineHeight: "24px",
    letterSpacing: "-0.2px",
    verticalAlign: "middle",
  },
  headingMd: {
    fontFamily: "Inter, sans-serif",
    fontWeight: fontWeights.medium,
    fontSize: "15px",
    lineHeight: "22px",
    letterSpacing: "-0.1px",
    verticalAlign: "middle",
  },
  headingSm: {
    fontFamily: "Inter, sans-serif",
    fontWeight: fontWeights.medium,
    fontSize: "13px",
    lineHeight: "20px",
    letterSpacing: "0px",
    verticalAlign: "middle",
  },
  headingForm: {
    fontFamily: "Inter, sans-serif",
    fontWeight: fontWeights.medium,
    fontSize: "12px",
    lineHeight: "16px",
    letterSpacing: "0px",
    verticalAlign: "middle",
  },
  bodyPrimary: {
    fontFamily: "Inter, sans-serif",
    fontWeight: fontWeights.medium,
    fontSize: "13px",
    lineHeight: "20px",
    letterSpacing: "0px",
    verticalAlign: "middle",
  },
  bodyMdMono: {
    fontFamily: "'Roboto Mono', monospace",
    fontWeight: fontWeights.normal,
    fontSize: "13px",
    lineHeight: "20px",
    letterSpacing: "0px",
    verticalAlign: "middle",
  },
  bodySecondary: {
    fontFamily: "Inter, sans-serif",
    fontWeight: fontWeights.semibold,
    fontSize: "13px",
    lineHeight: "20px",
    letterSpacing: "0px",
    verticalAlign: "middle",
  },
  bodyXs: {
    fontFamily: "Inter, sans-serif",
    fontWeight: fontWeights.normal,
    fontStyle: "medium",
    fontSize: "11px",
    lineHeight: "12px",
    letterSpacing: "0px",
    verticalAlign: "middle",
  },
  ["Text-body/secondary/secondary"]: {
    fontFamily: "Inter, sans-serif",
    fontStyle: "normal",
    fontWeight: fontWeights.normal,
    fontSize: "11px",
    lineHeight: "16px",
    letterSpacing: "0px",
    verticalAlign: "middle",
  },
  ["Text-body/primary/primary"]: {
    fontFamily: "Inter, sans-serif",
    fontStyle: "normal",
    fontWeight: fontWeights.normal,
    fontSize: "13px",
    lineHeight: "20px",
    letterSpacing: "0px",
    verticalAlign: "middle",
  },
  ["heading/primary"]: {
    fontFamily: "Inter, sans-serif",
    fontStyle: "normal",
    fontWeight: fontWeights.medium,
    fontSize: "15px",
    lineHeight: "22px",
    letterSpacing: "-0.1px",
    verticalAlign: "middle"
  },
  ["heading/form titles"]: {
    fontFamily: "Inter, monospace",
    fontStyle: "normal",
    fontWeight: fontWeights.semibold,
    fontSize: "12px",
    lineHeight: "16px",
    letterSpacing: "0px",
    verticalAlign: "middle",
  },
};

export type TextVariant = keyof typeof ThemeText;
